config/routes.rb
Rails.application.routes.draw do
  devise_for :exhibitions, controllers: {sessions: 'exhibitions/sessions', passwords: 'exhibitions/passwords', registrations: 'exhibitions/registrations',
   }
  resources :exhibitions, only: [:index, :show]

  devise_for :customers, controllers: {sessions: 'customers/sessions', passwords: 'customers/passwords', registrations: 'customers/registrations' }
  
  
  resources :items do
    resources :purchases, only: [:index, :create]
  end
  # get 'items/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'items#index'
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">


  <ul>
  
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
    
    
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    だれでもかんたん、もったいないをなくせる
  </p>
  <h2 class='ad-footer-title'>
    今すぐダウンロード
  </h2>
</div>
<%# //下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='mottainai-details'>
      <h2 class='footer-content-head'>MOTTAINAIについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'MOTTAINAI利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='mottainai-details'>
      <h2 class='footer-content-head'>MOTTAINAIを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'ブランド一覧', "#", class: "footer-link" %></li>
        <div class='store-btn'>
          <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
          <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
      </div>
      </ul>
    </div>
    <div class='mottainai-details'>
      <h2 class='footer-content-head'>MOTTAINAIについて</h2>
      <ul>
        <li><%= link_to 'MOTTAINAIガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'MOTTAINAIロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <p>© MOTTAINAI</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
 <%= link_to "MOTTINAI", "/", class: "top-title"%>

  <div class='nav'>
    <% if exhibition_signed_in? && !customer_signed_in? %>
      <ul class='lists-left'>
        <li>
        
          <%= link_to current_exhibition.company_name, "/exhibitions/#{current_exhibition.id}", class: "login-ex"%>
          
        </li>
        
        <li>
          <%= link_to 'ログアウト', destroy_exhibition_session_path, method: :delete, class: "sign-up-ex"  %>
        </li>
      </ul>
      <ul class='lists-right'>
        <li>
          <%= link_to 'ログイン', new_customer_session_path, class: "login" %>
        </li>
        <li>
          <%= link_to '新規登録', new_customer_registration_path, class: "sign-up" %>
        </li>
      </ul>

    <% elsif !exhibition_signed_in? && customer_signed_in? %>
      <ul class='lists-left'>
        <li>
          <%= link_to 'ログイン(EX)', new_exhibition_session_path, class: "login-ex" %>
        </li>
        <li>
          <%= link_to '新規登録(EX)', new_exhibition_registration_path, class: "sign-up-ex" %>
        </li>
      </ul>
      <ul class='lists-right'>
        <li>
          <%= link_to current_customer.nickname, "#", class: "user-nickname"%>
        </li>
        <li>
          <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: "logout" %>
        </li> 
      </ul>

    <% else %>
      <ul class='lists-left'>
        <li>
          <%= link_to 'ログイン(EX)', new_exhibition_session_path, class: "login-ex" %>
        </li>
        <li>
          <%= link_to '新規登録(EX)', new_exhibition_registration_path, class: "sign-up-ex" %>
        </li>
      </ul>
      <ul class='lists-right'>
        <li>
          <%= link_to 'ログイン', new_customer_session_path, class: "login" %>
        </li>
        <li>
          <%= link_to '新規登録', new_customer_registration_path, class: "sign-up" %>
        </li>
      </ul>
    <% end %>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
  
    <p class='second-fotter-text'>プライバシーポリシー</p>
    
    <p class='second-fotter-text'>MOTTAINAI利用規約</p>
    
    <p class='second-fotter-text'>特定商取引に関する表記</p>
    
  </div>
  
  <%= link_to "TOP戻る", '/', class:"second-fotter-logo"%>
</footer>

app/views/shared/_third-header.html.erb
<header class='top-page-header'>
<% if exhibition_signed_in? && !customer_signed_in? %>
  <a href="/items/new" >
    <div class='purchase-btn'>
      <span class='purchase-btn-text'>出品する</span>
        <%= image_tag 'camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
    </div>
  </a>
<% end %>

  <h2 class='service-title'>
    <%= @exhibition.company_name %>
  </h2>
  <div class='nav'>
    <% if exhibition_signed_in? && !customer_signed_in? %>
      <ul class='lists-left'>
        <li>
          <%= link_to 'TOPへ戻る', "/", class: "login-ex"%>
        </li>
        <li>
          <%= link_to 'ログアウト', destroy_exhibition_session_path, method: :delete, class: "sign-up-ex"  %>
        </li>
      </ul>
      <ul class='lists-right'>
        <li>
          <%= link_to 'ログイン', new_customer_session_path, class: "login" %>
        </li>
        <li>
          <%= link_to '新規登録', new_customer_registration_path, class: "sign-up" %>
        </li>
      </ul>

    <% elsif !exhibition_signed_in? && customer_signed_in? %>
      <ul class='lists-left'>
        <li>
          <%= link_to 'ログイン(EX)', new_exhibition_session_path, class: "login-ex" %>
        </li>
        <li>
          <%= link_to '新規登録(EX)', new_exhibition_registration_path, class: "sign-up-ex" %>
        </li>
      </ul>
      <ul class='lists-right'>
        <li>
          <%= link_to current_customer.nickname, "#", class: "user-nickname"%>
        </li>
        <li>
          <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: "logout" %>
        </li> 
      </ul>

    <% else %>
      <ul class='lists-left'>
        <li>
          <%= link_to 'ログイン(EX)', new_exhibition_session_path, class: "login-ex" %>
        </li>
        <li>
          <%= link_to '新規登録(EX)', new_exhibition_registration_path, class: "sign-up-ex" %>
        </li>
      </ul>
      <ul class='lists-right'>
        <li>
          <%= link_to 'ログイン', new_customer_session_path, class: "login" %>
        </li>
        <li>
          <%= link_to '新規登録', new_customer_registration_path, class: "sign-up" %>
        </li>
      </ul>
    <% end %>
  </div>
</header>