config/routes.rb
Rails.application.routes.draw do
  devise_for :exhibitions, controllers: {sessions: 'exhibitions/sessions', passwords: 'exhibitions/passwords', registrations: 'exhibitions/registrations',
   }
  resources :exhibitions, only: [:index, :show]

  devise_for :customers, controllers: {sessions: 'customers/sessions', passwords: 'customers/passwords', registrations: 'customers/registrations' }
  
  
  resources :items do
    resources :purchases, only: [:index, :create]
  end
  # get 'items/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'items#index'
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :exhibition
  has_one :purchase
  has_one_attached :image

  belongs_to_active_hash :category
  belongs_to_active_hash :item_status

  with_options presence: true do
    validates :name, length: { maximum: 40 }
    validates :text, length: { maximum: 100 }
    validates :category, :item_status
    with_options numericality: true do
      validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 50, less_than_or_equal_to: 99_999, message: :'Out of setting range' }
    end
  end
  with_options numericality: { other_than: 0 } do
    validates :category_id
    validates :item_status_id
    validates :exhibition_id
  end
  validates :weight, numericality: { greater_than_or_equal_to: 0.1, less_than_or_equal_to: 15 }
  validates :cost, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 100_000 }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # before_action :authenticate_customer!
  # skip_before_action :authenticate_customer!, only: [:index, :show]
  before_action :authenticate_exhibition!
  skip_before_action :authenticate_exhibition!, only: [:index, :show]
  # before_action :move_to_index, except: [:index, :show]
  # customer!もindexとshowと購入しかできないようにしたいから制限したいあっちで設定
  before_action :set_item, only: [:show, :destroy, :edit, :update]

  def index
    @items = Item.order('created_at DESC').includes(:exhibition)
    # gon.exhibition = current_exhibition
    # gon.customer = current_customer
    gon.user = if customer_signed_in?
                 current_customer
               elsif exhibition_signed_in?
                 current_exhibition
               else
                 Customer.new(latitude: 35.681236, longitude: 139.767125)
               end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if exhibition_signed_in? && current_exhibition.id == @item.exhibition.id && @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    if exhibition_signed_in? && current_exhibition.id == @item.exhibition.id
      @item.delete
      redirect_to root_path
    else
      render :show
    end
  end

  private

  # def move_to_index
  #   if customer_signed_in? && @customer.id == current_customer.id
  #     redirect_to action: :index
  #   end
  # end

  def item_params
    params.require(:item).permit(:image, :name, :text, :category_id, :price, :exhibition_id, :item_status_id, :cost, :weight).merge(exhibition_id: current_exhibition.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<%# app/assets/stylesheets/items/new.css %>

<div class="items-sell-contents">
  <header class="items-sell-header">
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model:@item, method: :patch, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,00文字まで）こちら大量入荷した際の余りで、賞味期限が近くなりました。品質の方は問題ございません" ,rows:"5" ,maxlength:"100" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          個数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:item_status_id, ItemStatus.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥50〜99,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格(税込)</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" ,maxlength:"7"%>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </span>
        </div>
      </div>
    </div>
    <%# /販売価格 %>

    <%# その他 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>その他<br>元値は購入者には見せない仕様となっております</span>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>元値</span>
            <span class="indispensablenini">任意</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :cost, class:"price-input", id:"item-cost", placeholder:"例）300" ,maxlength:"7"%>
        </div>
        <div class="price-content">
          <div class="price-text">
            <span>重量</span>
            <span class="indispensablenini">任意</span>
          </div>
          <span class="sell-yen">kg</span>
          <%= f.text_field :weight, class:"price-input", id:"item-price", placeholder:"例0.1〜15" ,maxlength:"7"%>
        </div>
      </div>
    </div>
    <%# /その他 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <p class="inc">
      @MOTTAINAI,Inc.
    </p>
  </footer>
</div>

app/views/items/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「もったいないをなくす」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      もったいないをなくす
    </h2>
    <p class='service-explain-mein'>
      『まだ食べれるのに、、、』
    </p>
    <p class='service-explain'>
      「在庫はあるのに賞味期限間近だから販売できない、、、」
    </p>
    <p class='service-explain'>
      「袋に穴空いたけどすぐテープで塞いだのにな、、、」
    </p>
    <p class='service-explain'>
      「この捨てている時間はなんなのだろうか、、、」
    </p>
    <p class='service-explain'>
      そう思ったお店とお客さまを結び合わせる
    </p>
    <p class='service-explain'>
      そんなアプリです
    </p>
  </div>
  <%# //画面上部の「人生を変えるフリマアプリ」帯部分  %>

  <%# MOTTAINAIが選ばれる3つの理由部分 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      MOTTAINAIで食資源を大切にしよう
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "food_syokuhin_haikibutsu.png", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>643万t</span>
          日本の食品年間ロス
        </h3>
        <p class='reason-list-description'>
          アプリを使い資源を大切に使おう！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "amabie_reji.png", class:"list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>お店</span>
          のムリ・ムダ・ムラ軽減！
        </h3>
        <p class='reason-list-description'>
          簡単投稿で時間も節約できます！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "nefuda_yasui.png", class:"list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>お客様</span>
          スペシャルプライスでご購入
        </h3>
      </li>
    </ul>
  </div>
  <%# //MOTTAINAIが選ばれる3つの理由部分 %>

  <%# 画面中央の「物が溢れる時代」帯部分 %>
  <div class='ad-contents'>
    <h2 class='ad-title'>
      物が溢れる時代
    </h2>
    <p class='ad-explain'>
      企業系の年間食品廃棄は1970万t、その内まだ食べれる分は352万t
    </p>
    <p class='ad-explain'>
      家庭での年間食品廃棄は789万t、その内まだ食べれる分は291万tもあります
    </p>
    <p class='ad-explain'>
      正しい消費社会を目指そう！！
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# //画面中央の「物が溢れる時代」帯部分 %>

  <%# GOOGLE MAP %>
  <div class='feature-contents'>
    <h2 class='title'>
      近隣MAP
    </h2>
    <%#<ul class='feature-lists'>%>
    <!-- 地名入力用のinputを追加 -->

    <input id="address" type="textbox" value="" >

    <!-- buttonをクリックしたらcodeAddressを実行-->
    <input type="button" value="検索" onclick="codeAddress()">
    <div id='map'></div>

    <script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GMAP_API_KEY']%>&callback=initMap" async defer></script>

    <%#</ul>%>
  </div>
  <%# //GOOGLE MAP %>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>出品されている商品一覧</h2>
    <h3 class="subtitle" >現在まで取引で減少した資源は
    <h2 class='title'>
      <%array = []%>
        <% @items.each do |item| %>
          <% if item.purchase %>
            <% array << item.weight.to_f %>
          <% end %>
        <% end %>
      <%= array.sum%>kg
    </h2>
    </h3>
    
    <ul class='item-lists'>
      <% if  @items.present? %> 
        <% @items.each do |item| %>
        
          <li class='list'>
            <%= link_to item_path(item.id) do %>
              <div class='item-img-content'>
                <%= image_tag item.image, class: "item-img" if item.image.attached? %>

                <%# 商品が売れていればsold outの表示 %>
                <% if item.purchase.present? %>
                  <div class='sold-out'>
                    <span>Sold Out!!</span>
                  </div>
                <% end %>
                <%# //商品が売れていればsold outの表示 %>

              </div>
              <div class='item-info'>
                <h3 class='item-name'>
                  <%= item.name %>
                </h3>
                <div class='item-price'>
                  <span><%= item.price %>円<br>(税込み)</span>
                  <div class='star-btn'>
                    <span class='star-count'><%= item.exhibition.city%></span>
                  </div>
                </div>
              </div>
            <% end %>
          </li>
        <%end%>
          <%# 商品がない場合のダミー %>
      <% else %>
        <li class='list'>
          <%= link_to '#' do %>
            <%= image_tag "sample.png", class: "item-img" %>
            <div class='item-info'>
              <h3 class='item-name'>
                まだ出品されていません
              </h3>
              <div class='item-price'>
                <span>99999999円<br>(税込み)</span>
                <div class='star-btn'>
                  <span class='star-count'>住所</span>
                </div>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
              <%# //商品がない場合のダミー %>
    </ul>
  </div>
  <%# //商品一覧 %>
</div>
<% if exhibition_signed_in? && !customer_signed_in? %>
  <a href="/items/new" >
    <div class='purchase-btn'>
      <span class='purchase-btn-text'>出品する</span>
        <%= image_tag 'camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
    </div>
  </a>
<% end %>

<%= render "shared/footer" %>

app/views/items/new.html.erb
<div class="items-sell-contents">
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model:@item, method: :post, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,00文字まで）こちら大量入荷した際の余りで、賞味期限が近くなりました。品質の方は問題ございません" ,rows:"5" ,maxlength:"100" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          個数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:item_status_id, ItemStatus.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥50〜99,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格(税込)</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" ,maxlength:"7"%>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </span>
        </div>
      </div>
    </div>
    <%# /販売価格 %>

    <%# その他 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>その他<br>元値は購入者には見せない仕様となっております</span>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>元値</span>
            <span class="indispensablenini">任意</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :cost, class:"price-input", id:"item-cost", placeholder:"例）300" ,maxlength:"7"%>
        </div>
        <div class="price-content">
          <div class="price-text">
            <span>重量</span>
            <span class="indispensablenini">任意</span>
          </div>
          <span class="sell-yen">kg</span>
          <%= f.text_field :weight, class:"price-input", id:"item-price", placeholder:"例0.1〜15" ,maxlength:"7"%>
        </div>
      </div>
    </div>
    <%# /その他 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to "TOP戻る", '/', class:"second-fotter-logo"%>
    <p class="inc">
      ©︎MOTAINAI,Inc.
    </p>
  </footer>
</div>

app/views/items/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.name %>
    </h2>
    <div class='item-img-content'>
      <%= image_tag @item.image,class:"item-box-img" if @item.image.attached? %>
        <% if @item.purchase.present? %>
          <div class='sold-out'>
            <span>Sold Out!!</span>
          </div>
        <% end %>
    </div>
    <div class="item-price-box">
      <span class="item-price">
        <%= @item.price %>円
      </span>
    </div>

    <%# ログインしているユーザと出品しているユーザが同一人物の時、商品の編集と削除を表示%>
    <% if exhibition_signed_in? &&current_exhibition.id == @item.exhibition.id %>
      <%= link_to '商品の編集', edit_item_path, method: :get, class: "item-red-btn" %>
      <p class='or-text'>or</p>
      <%= link_to '削除', item_path, method: :delete, class:'item-destroy' %>
    <% elsif !exhibition_signed_in? && !@item.purchase.present? %>

      <%= link_to '購入画面に進む', item_purchases_path(@item.id) ,class:"item-red-btn"%>
    <% end %>

    <div class="item-explain-box">
      <div>  商品説明 </div>
      <span><%= @item.text %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value">
          <%= link_to @item.exhibition.company_name, "/exhibitions/#{@item.exhibition.id}"%>
          </td>
        </tr>
        <tr>
          <th class="detail-item">出品住所</th>
          <td class="detail-value">
          <% juusyo = (@item.exhibition)%>
          <%= (juusyo.prefecture.name) + (juusyo.city) +(juusyo.building_name) %></td>
        </tr>
        
        <tr>
          <th class="detail-item">個数</th>
          <td class="detail-value"><%= @item.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= @item.item_status.name %></td>
        </tr>

      </tbody>
    </table>
  </div>
   <%# 商品の概要 %>

  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
  <%#
  <a href="#" class='another-item'><%= "商品のカテゴリー名" %><%#をもっと見る</a>%>
</div>